# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-10 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='telephone',
            field=models.CharField(max_length=15),
        ),
    ]
