# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-14 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20180310_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='telephone',
            field=models.CharField(max_length=20),
        ),
    ]
